### ISSUE TITLE
Ruuvigw2mqtt broken due to recent upgrade of s6-overlay

### ISSUE THREAD

**Issue by n1koo** [kirbo/ruuvigw-mqtt-to-ha-auto-discovery#1]
Since a recent upgrade in [HA image builds](https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/) the `ruuvigw2mqtt` has failed to start with error: `s6-overlay-suexec: fatal: can only run as pid 1`

The problem seems to be exactly same as what you addressed in https://github.com/Kirbo/ha-addons-repository/commit/8296b4aca6c7c002d8f4bf07b890b74394af73ee but would be awesome to also get it for `ruuvigw2mqtt` :)

**Comment by Kirbo** [comment]
Hi @n1koo, the same fix should now be done to ruuvigw2mqtt as well. Let me know if the problem persists (don't have time to actually verify it right now).
If the problem is fixed, could you please close this issue? 🙂

**Comment by n1koo** [comment]
Thanks @Kirbo ! Now it works again
